const types = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  TILE_START_LOADING: 'TILE_START_LOADING',
  TILE_STOP_LOADING: 'TILE_STOP_LOADING',
  SET_POSITION: 'SET_POSITION',
  SCENE_ADD: 'SCENE_ADD',
  SCENE_REMOVE: 'SCENE_REMOVE',
  SCENE_CHANGE_BANDS: 'SCENE_CHANGE_BANDS',
  SCENE_PIPELINE_ADD_STEP: 'SCENE_PIPELINE_ADD_STEP',
  SCENE_PIPELINE_REMOVE_STEP: 'SCENE_PIPELINE_REMOVE_STEP',
  SCENE_PIPELINE_INDEX_STEP: 'SCENE_PIPELINE_INDEX_STEP',
  SCENE_PIPELINE_EDIT_STEP: 'SCENE_PIPELINE_EDIT_STEP',
  SET_ERROR: 'SET_ERROR',
};

export default types;
